name: Task4 workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Task4/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Task4/**'
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Task4/dockerfile
        push: false
        load: true
        tags: zig-test:latest

    - name: Run Zig tests
      run: docker run --memory 4g zig-test:latest
