name: Task5 workflow

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Task1/dockerfile
        push: false
        load: true
        tags: test:latest

    - name: Run tests
      run: docker run test:latest
